default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME_DB'] %>
  password: <%= ENV['PASSWORD_DB'] %>
  host: <%= ENV['HOST_DB'] %>
  port: <%= ENV['PORT_DB'] %>

development:
  <<: *default
  database: finance_api_development

test:
  <<: *default
  database: finance_api_test

production:
  <<: *default
  database: finance_api_production
  username: finance_api
  password: <%= ENV['FINANCE_API_DATABASE_PASSWORD'] %>
